### ISSUE TITLE
Publish to docker registry

### ISSUE THREAD

**Issue by vincentbernat** [spotify/docker-kafka#1]
Hi!

Could you publish your image to the Docker registry? Thanks!

**Comment by mbruggmann** [comment]
Sorry this got lost somehow... But we have a "spotify/kafka" image on docker hub now.
https://registry.hub.docker.com/u/spotify/kafka/

**Comment by vincentbernat** [comment]
Thanks!

**Comment by mpareja** [comment]
@mbruggmann are you folks running Kafka/Zookeeper Dockerized in production?

**Comment by mbruggmann** [comment]
@mpareja not yet, we mostly use this image for integration testing purposes.

**Comment by mpareja** [comment]
Thanks for the response, :+1:.
