### ISSUE TITLE
Update Kafka to the latest version (0.8.2.1)

### ISSUE THREAD

**Issue by alexandrnikitin** [spotify/docker-kafka#4]

**Comment by guizmaii** [comment]
Have you seen this fork of this repo : https://github.com/AhmedSoliman/docker-kafka ? Kafka is updated !

;)

**Comment by pires** [comment]
Or you can just merge https://github.com/spotify/docker-kafka/pull/11, build and use your own version.

**Comment by blawlor** [comment]
Yep - sorry. I saw @guizmaii 's ticket after I created the push request.

**Comment by alexandrnikitin** [comment]
Closed by #17
